### ISSUE TITLE
Doesn't work in node_modules

### ISSUE THREAD

**Issue by mizchi** [jnordberg/coffeeify#21]
I tried this module hack https://github.com/substack/browserify-handbook#avoiding-

```
app/
  - foo.coffee
  - initialize.coffee
node_modules/
  app -> ../app # alias to app
```

`require('app/foo')` in `initialize.coffee` doesn't work. (maybe it is handled as pure javascript)

Is this in coffeeify role?

**Comment by sethlivingston** [comment]
This is covered in the Browserify issue https://github.com/substack/node-browserify/issues/993.

To summarize, the solution is to add a package.json file to the symlinked folder to "re-state" your transforms. My package.json is simply,

```
{
  "browserify": {
    "transform": ["coffeeify"]
  }
}
```

And I echo the thanks for maintaining Coffeeify!
