### ISSUE TITLE
Would it be possible to tell browserify to look for index.coffee ?

### ISSUE THREAD

**Issue by QuentinFchx** [jnordberg/coffeeify#25]
According to the [browserify documentation](https://github.com/substack/node-browserify#packagejson), when you require a module/folder, it looks for an `index.js` file.
Would it be possible with coffeeify to tell browserify to look for `index.coffee` instead ?

**Comment by honi** [comment]
Try adding ```extensions: ['.coffee']``` to browserify options.

**Comment by jnordberg** [comment]
What @honi said, or `--extension .coffee` if running from command line.
