### ISSUE TITLE
where do I see syntax errors, etc.?

### ISSUE THREAD

**Issue by mark-hahn** [jnordberg/coffeeify#35]
When I have a syntax error I just see `undefined` in my browser window.  The terminal that the beefy server is running in shows nothing.  Where do I see syntax errors, etc.?  I'm sorry if this is a stupid question.

My command (as the terminal shows it when a request is served) ...

```
./node_modules/browserify client/app.coffee -d -o bundle.js -t coffeeify --extension .coffee
```

**Comment by jnordberg** [comment]
They should show just as javascript syntax errors would.

```
> ./node_modules/.bin/browserify -t . example/error.coffee
/Users/jnordberg/Development/coffeeify/example/error.coffee:5
thisIsWrong = , 'waaa'
              ^
ParseError: unexpected ,
```

**Comment by jnordberg** [comment]
Closing this, feel free to reopen if this is still a problem
