### ISSUE TITLE
Upgrade to coffeescript 1.10.0

### ISSUE THREAD

**Issue by QuentinFchx** [jnordberg/coffeeify#36]
As a side node, why do we force a coffeescript version in this package ?
We could let it to the developer discretion, shouldn't we ?

**Comment by elgubenis** [comment]
good idea

**Comment by jnordberg** [comment]
Updated and published as 1.2.0.

Don't know if i like the idea, how would we handle a change in coffee-script's api?

**Comment by lzrski** [comment]
I'd like to be able to supply different coffee compiler to coffeeify. One use case is to play with unmerged branches of coffee-script (e.g. from open PRs) or forks.

Maybe a solution would be to ship default version of coffee with coffeeify, but let users supply different one via an option?
