### ISSUE TITLE
Problem passing transform options with grunt-browserify

### ISSUE THREAD

**Issue by cueedee** [jnordberg/coffeeify#38]
After upgrading from version `1.2.0` to any version `2.0.0`-`2.0.1`, in an otherwise unchanged environment, I can no longer see the CoffeeScript source in Chrome's debugger.

This is with [`browserify@11.2.0`](https://github.com/substack/node-browserify/tree/11.2.0), loaded as a dependency of [`grunt-browserify@4.0.1`](https://github.com/jmreidy/grunt-browserify/tree/v4.0.1) (which is the latest at the time of writing).

Transforms are configured in `package.json`:
```json
  ...
  "browserify": {
    "transform": [
      "coffeeify",
      "hbsfy",
      "browserify-shim"
    ]
  },
  ...
```

Options passed into `browserify` from `grunt-browserify`:
```json
  "detectGlobals": true,
  "extensions": [
    ".coffee",
    ".hbs"
  ],
  "noParse": [
    "jquery"
  ],
  "debug": true
```

Note that the `debug` flag **is** enabled.

However, best as I can tell, the `options` argument to `coffeeify( ... ){ ... }` is always an empty object. Excerpt from: [`index.js`](https://github.com/jnordberg/coffeeify/blob/2.0.1/index.js#L79):
 
```js
...
function coffeeify(filename, options) {
    if (!isCoffee(filename)) return through();

    if (typeof options === 'undefined' || options === null) options = {};

    var compileOptions = {
        sourceMap: (options._flags && options._flags.debug),
        bare: true,
        header: false
    };
    ...
```

**Comment by jnordberg** [comment]
Looks like only the browserify cli is passing the debug flag. It's not done automatically when using browserify programatically. Did you try passing transform options as described in https://github.com/jmreidy/grunt-browserify/tree/v4.0.1#transform?
