### ISSUE TITLE
Source maps broken when using with coffee-script 1.11.*

### ISSUE THREAD

**Issue by lzrski** [jnordberg/coffeeify#41]
When using with coffee-script 1.11.0 or 1.11.1 (latest at the time of reporting) this command:

```bash
browserify --debug --transform coffeeify --extension .coffee --outfile build/application.js src/index.coffee
```

produces a bundle with source maps that make Chrome Dev Tools display files with `.coffee` extensions, but compiled JS content, whit source maps string at the bottom:

<img width="677" alt="screen shot 2016-11-03 at 14 01 34" src="https://cloud.githubusercontent.com/assets/1684495/19966894/18e29bfc-a1ce-11e6-8330-e1a9a3827cb4.png">

It might be related to change in lexer and parser announced in [the changelog](http://coffeescript.org/#changelog) for v. 1.11.0:

> Improved the internal representation of a CoffeeScript program. This is only noticeable to tools that use `CoffeeScript.tokens` or `CoffeeScript.nodes`. Such tools need to update to take account for changed or added tokens and nodes.

I don't think it's a bug in CS, as the source maps are generated correctly if I do it like that:

```bash
coffee -cMo build/js/ src/
browserify --debug --outfile build/application.js build/js/index.js
```

**Comment by jnordberg** [comment]
Published as 2.1.0

Let me know if there is any problems
