### ISSUE TITLE
Allow `transpile` option to process JSX

### ISSUE THREAD

**Issue by suprMax** [jnordberg/coffeeify#43]
Currently compiler crashes because it can't compile JSX without this flag. When calling coffeescript programmatically it expects a babelrc configuration object. Why not simply allow to pass it through? Or  pass through all unknown compiler options for future compatibility?

Something like this: https://github.com/jnordberg/coffeeify/pull/44/files

**Comment by jnordberg** [comment]
pr merged, if it makes sense, could you add a test for the transpile option?

**Comment by suprMax** [comment]
I didn't do it because I would essentially be testing coffeescript which doesn't make sense. What would be good to add is a check that options are passed along untouched, for that I would have to add a new test with proxyquire and mock coffeescript compile function. If you're ok with one more devDependency, I could do that yea.

**Comment by jnordberg** [comment]
Sounds good, go for it. new devDeps are fine

**Comment by jnordberg** [comment]
Fixed in 3.0.1

**Comment by cueedee** [comment]
Isn't it slightly strange to have the CoffeeScript compiler invoke babel (trough `--transpile`), while the same -  this being a browserify context - could be achieved through [`babelify`](https://github.com/babel/babelify#readme)?

Just curious, because I, too, thought I really needed the `--transpile` option (in this case, to compile to ES5) until I realised that actually, I didn't.

**Comment by max-degterev** [comment]
I had all my JSX files with .es extension to make sure I can differentiate what I can run in node and what I need to precompile. I didn't manage to do that via babelify alone, but perhaps it is possible. Do you have a working solution?

Update:

@cueedee you are right, this also works:
```
bundler.transform(require('coffeeify'));
bundler.transform(require('babelify').configure({ extensions: ['.es', '.coffee'] }));
```

I suppose having unknown options passed down is still useful for future versions compatibility though.

**Comment by cueedee** [comment]
Being unfamiliar with JSX, it's a bit hard to define "working" in that context, but the `package.json` excerpt below is what made `babelify` play nice with the other `transform`-s for me.  The `extensions` section especially is the instrumental bit that I somehow had to figure out the hard way. 

```json
...
  "browserify": {
    "transform": [
      "coffeeify",
      "hbsfy",
      [
        "babelify",
        {
          "extensions": [
            ".coffee",
            ".hbs"
          ],
          "presets": [
            "env"
          ]
        }
      ],
      "browserify-shim"
    ]
  },
...
```

I opted not to use a separate `.babelrc` btw.
