### ISSUE TITLE
Keep generated .js files

### ISSUE THREAD

**Issue by nickdima** [jnordberg/coffeeify#9]
Is is possible to save the transformed coffee sources as js files so they can be required in node?
I'm using coffeeify with grunt and it works perfect for generating my client bundle and it would be great if I didn't have to use something else for generating the js files again.

**Comment by nmccready** [comment]
This is a really useful feature that should be added. It is in [webpack](https://github.com/webpack/coffee-loader/blob/master/index.js) by default . I am constantly running into the cases that the coffee sourcemapped code is impossible to debug. Impossible meaning breakpoints do not trip correctly . Also debugging straight js is way easier.

I pointed you to the webpack code for coffee-loader as I am trying to figure out how to retrofit this in. 



> You could set something up compile all the coffeescript and then run browserify on that

The problem with this is it is double the overhead and browserify's watchify is efficient . It would be pretty ugly to have a gulp-coffee task and then browserify the js of that. 

Anyway I know it can be done in this part of the code; it's just a matter of figuring out this line
https://github.com/webpack/coffee-loader/blob/master/index.js#L22.

**Comment by jnordberg** [comment]
I think that it would be way uglier to add side effects to what should be a simple transform function.

**Comment by nmccready** [comment]
I just figured it out and it was so easy I have no idea why it is not inhere. There is no side effect and you can debug either coffee or js at the same time.

**Comment by nmccready** [comment]
Testing it some more to make sure; I'll make a PR.

**Comment by jnordberg** [comment]
Maybe I'm misunderstanding what you want to do. Are you proposing to store copies of the generated javascript or something else?

**Comment by nmccready** [comment]
Well webpack doesnt store the compiled js file except for maybe in the browsers caching / local storage . Anyhow just putting in the generatedFile code gets both the coffee and js in the browser. Ill fork and show u the lines.

**Comment by jnordberg** [comment]
Sounds interesting!
